### ISSUE TITLE
No support for IPv6 addresses

### ISSUE THREAD

**Issue by rafaelhribeiro** [Oaklight/Vesper#7]
Vesper does not support IPv6 addresses and throws an error when I try to use them. Actually, it works if I put the IPv6 addresses in the `/etc/hosts` file as a workaround.
The error listed below occurs when I insert the following entry `http://[fcff:8::1]:5000` as an input in the `ip_lists.txt` file.

```
Traceback (most recent call last):
  File "server.py", line 79, in <module>
    http, host, port = my_ip.split(':')
ValueError: too many values to unpack (expected 3)
```

**Comment by Oaklight** [comment]
Hi Rafael, interesting indeed. Back in 2019 when we designed this, it was meant for a course project and we didn't consider using IPv6 during development. We may look into this, but at this moment, please stick to IPv4 instead. Thanks :)
